from Card import Card
from PlayerHand import PlayerHand

c = Card("H", "K")
# c1 = Card("H", "A")
print(c.suit)
print(c.rank)
# print(c1.suit)
# print(c1.rank)
# print(c == c1)
c.convertCard()
# c1.convertCard()
# print(c == c1)
print(c.suit)
print(c.rank)
# print(c1.suit)
# print(c1.rank)
# c.convertCardBack()
# c1.convertCardBack()
# print(c > c1)
# def test_CardFuncs():
#     c = Card("s", "3")
#     c1 = Card("H", "A")
#     print(c.suit)
#     print(c.rank)
#     print(c1.suit)
#     print(c1.rank)
#     print(c > c1)
# def test_PlayerHandFuncs():
hand = PlayerHand()
hand.put('D', 'A')
hand.put('S', 'K')
hand.put('S', '2')
hand.put('C', 'Q')
hand.put('H', '7')
hand.put('S', 'K')
hand.put('C', 'K')
print(hand.inOrder())
print(hand.getMin())